### PR TITLE
Solve Task 2

### PR DESCRIPTION
**Pull request by criticic**
Issue: #2

### CODE REVIEW

**Comment by Shashank1985** [comment]
@criticic your code must return a csv file, pls do the required changes

**Comment by criticic** [comment]
okay sure

**Comment by criticic** [comment]
@Shashank1985 I have updated the notebook

**Comment by Shashank1985** [comment]
Screenshot from 2023-12-19 15-40-05
please keep all the titles in the same cell, this is not what we were looking for. The scraped headlines should be in the same cell.

**Comment by criticic** [comment]
hmm I opened it on a online csv reader and it appeared fine

**Comment by criticic** [comment]
even in viscose it shows correct formatting,
image

**Comment by criticic** [comment]
I think in some apps it does not automatically detect the delimiter "|", so you'd have to add it.
image

**Comment by Shashank1985** [comment]
@criticic ok approved

**Pull request merged**
