### PR TITLE
Task 2 done

### PR DESCRIPTION
**Pull request by Jarviss77**
Issue: #2

### CODE REVIEW

**Comment by Shashank1985** [comment]
@Jarviss77 unable to open link on my end, please check the link

**Comment by Jarviss77** [comment]
Screenshot 2023-12-20 at 3 19 22 PM
 
i have added you as a viewer

**Comment by Shashank1985** [comment]
image
copy link and try sending it again

**Comment by Jarviss77** [comment]
https://colab.research.google.com/drive/1BTiGIGW94St2xOpnD6U74ea9rkcYhJl5

**Comment by Shashank1985** [comment]
@Jarviss77 the task was to scrape financial news in general and not news about a certain stock,  further you were to return a csv file with the headlines as the output. Please do the required changes

**Comment by Jarviss77** [comment]
Now check

**Pull request merged**
