### PR TITLE
Create iec2022060.txt

### PR DESCRIPTION
**Pull request by sarthakvermaa**
Issue: #2

### CODE REVIEW

**Comment by Shashank1985** [comment]
@sarthakvermaa for task 2, you were supposed to find the latest financial news, not the financial news related to a certain stock. Please change the code to scrape general financial news

**Comment by sarthakvermaa** [comment]
@Shashank1985 Task's description was quite vague in the description box. Since it was not mentioned earlier to scrap general financial news so I decided to scrape financial news of tcs. This will take a lot of changes in the code. Please consider this.

**Comment by Shashank1985** [comment]
@sarthakvermaa please look at the .ipynb file, it is said to scrape financial news in general

**Comment by sarthakvermaa** [comment]
@Shashank1985 Can you please look at it again

**Review by Shashank1985 — APPROVED** [review]

**Pull request merged**
